appx/Power BI Embedded/powerbi-sample-app/powerbi-sample-app/Models/DashboardViewModel.cs
using Microsoft.PowerBI.Api;
using Microsoft.PowerBI.Api.Beta.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace paas_demo.Models
{
    public class DashboardViewModel
    {
        public IDashboard Dashboard { get; set; }

        public List<Tile> Tiles { get; set; }
    }
}

appx/Power BI Embedded/powerbi-sample-app/powerbi-sample-app/Models/DashboardsViewModel.cs
using Microsoft.PowerBI.Api.Beta.Models;
using System.Collections.Generic;

namespace paas_demo.Models
{
    public class DashboardsViewModel
    {
        public List<Dashboard> Dashboards { get; set; }
    }
}

appx/Power BI Embedded/powerbi-sample-app/powerbi-sample-app/Models/ReportViewModel.cs
using Microsoft.PowerBI.Api;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace powerbi_sample_app.Models
{
    public class ReportViewModel
    {
        public IReport Report { get; set; }

        public string AccessToken { get; set; }
    }
}

appx/Power BI Embedded/powerbi-sample-app/powerbi-sample-app/Models/ReportsViewModel.cs
using Microsoft.PowerBI.Api;
using Microsoft.PowerBI.Api.Beta.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace powerbi_sample_app.Models
{
    public class ReportsViewModel
    {
        public IList<ReportWorkspace> Workspaces { get; set; }
    }

    public class ReportWorkspace
    {
        public string WorkspaceId { get; set; }
        public string DisplayName { get; set; }
        public IList<Report> Reports { get; set; }
    }
}

appx/Power BI Embedded/powerbi-sample-app/powerbi-sample-app/Controllers/DashboardController.cs
using System;
using System.Configuration;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using Microsoft.PowerBI.Api.Beta;
using Microsoft.PowerBI.Security;
using powerbi_sample_app.Models;
using powerbi_sample_app.Reporting;
using System.Collections.Generic;
using Microsoft.PowerBI.Api.Beta.Models;
using System.Web.Configuration;

namespace powerbi_sample_app.Controllers
{
    public class DashboardController : Controller
    {
        private string workspaceCollection;
        private ReportsViewModel workspaces;

        public DashboardController()
        {
            this.workspaceCollection = ConfigurationManager.AppSettings["powerbi:WorkspaceCollection"];
            this.workspaces = new ReportsViewModel
            {
                Workspaces = ConfigurationManager.AppSettings["WorkspaceMappings"]
                                .Split(new[] { ';' }, StringSplitOptions.RemoveEmptyEntries)
                                .Select(workspace => new ReportWorkspace
                                {
                                    WorkspaceId = workspace.Split('|')[0],
                                    DisplayName = workspace.Split('|')[1],
                                })
                                .ToList(),
            };
        }

        public ActionResult Index()
        {
            return View();
        }

        [ChildActionOnly]
        public ActionResult Reports()
        {
            var viewModel = new ReportsViewModel
            {
                Workspaces = this.workspaces.Workspaces
                    .Select(workspace => new ReportWorkspace
                    {
                        WorkspaceId = workspace.WorkspaceId,
                        DisplayName = workspace.DisplayName,
                        Reports = GetWorkspaceReports(workspace.WorkspaceId),
                    })
                    .ToList(),
            };
            return PartialView(viewModel);
        }

        private IList<Report> GetWorkspaceReports(string workspaceId)
        {
            using (var client = new PowerBIReportClient(this.workspaceCollection, workspaceId))
            {
                try
                {
                    return client.Reports.GetReports(this.workspaceCollection, workspaceId).Value;
                }
                catch
                {
                    return new List<Report>();
                }
            }
        }

        [HttpGet]
        public ActionResult Upload()
        {
            ViewBag.ReportCategory = this.workspaces.Workspaces
                .Select(workspace => new SelectListItem
                {
                    Text = workspace.DisplayName,
                    Value = workspace.WorkspaceId,
                });
            return View(new ReportUploadModel());
        }

        [HttpPost]
        public async Task<ActionResult> Upload(ReportUploadModel report)
        {
            string workspaceId = report.ReportCategory;
            // See if we have a new workspace name
            if (!String.IsNullOrWhiteSpace(report.NewReportCategory))
            {
                using (var client = new PowerBIReportClient(PowerBIToken.CreateProvisionToken(this.workspaceCollection), this.workspaceCollection, String.Empty))
                {
                    var newWorkspaceResult = await client.Workspaces.PostWorkspaceAsync(this.workspaceCollection);
                    this.workspaces.Workspaces.Add(new ReportWorkspace
                    {
                        DisplayName = report.NewReportCategory,
                        WorkspaceId = newWorkspaceResult.WorkspaceId,
                        Reports = new List<Report>(),
                    });
                    workspaceId = newWorkspaceResult.WorkspaceId;
                    // Update web.config
                    var webConfig = WebConfigurationManager.OpenWebConfiguration("~");
                    webConfig.AppSettings.Settings["WorkspaceMappings"].Value = String.Join(";", this.workspaces.Workspaces
                        .Select(workspace => String.Format("{0}|{1}", workspace.WorkspaceId, workspace.DisplayName)));
                    webConfig.Save();
                }
            }
            using (var client = new PowerBIReportClient(this.workspaceCollection, workspaceId))
            {
                var import = await client.Imports.PostImportWithFileAsync(this.workspaceCollection,
                    workspaceId,
                    report.PbixReport.InputStream,
                    report.ReportName);
                import = await client.WaitForImportToComplete(import);
                if (import.ImportState == PowerBIReportClient.StateSucceeded)
                {
                    return RedirectToAction("Report", new { workspaceId = workspaceId, reportId = import.Reports.First().Id });
                }
            }
            return RedirectToAction("Index");
        }

        public async Task<ActionResult> Report(string workspaceId, string reportId)
        {
            using (var client = new PowerBIReportClient(this.workspaceCollection, workspaceId))
            {
                var reportsResponse = await client.Reports.GetReportsAsync(this.workspaceCollection, workspaceId);
                var report = reportsResponse.Value.FirstOrDefault(r => r.Id == reportId);
                var embedToken = PowerBIToken.CreateReportEmbedToken(this.workspaceCollection, workspaceId, report.Id);

                var viewModel = new ReportViewModel
                {
                    Report = report,
                    AccessToken = embedToken.Generate(PowerBIReportClient.SigningKey)
                };

                return View(viewModel);
            }
        }

        /*public async Task<JsonResult> ViewReport(string details, string reportId)
        {
            using (var client = new PowerBIReportClient(this.workspaceCollection, this.workspaceId))
            {
                var reportsResponse = await client.Reports.GetReportsAsync(this.workspaceCollection, this.workspaceId);
                var report = reportsResponse.Value.FirstOrDefault(r => r.Id == reportId);
                var embedToken = PowerBIToken.CreateReportEmbedToken(this.workspaceCollection, this.workspaceId, report.Id);

                return Json(new
                {
                    Report = report,
                    AccessToken = embedToken.Generate(PowerBIReportClient.SigningKey)
                });
            }
        }*/
    }
}

appx/Power BI Embedded/powerbi-sample-app/powerbi-sample-app/Controllers/ReportsController.cs
using Microsoft.PowerBI.Api.Beta;
using Microsoft.PowerBI.Security;
using Microsoft.Rest;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Http;

namespace paas_demo.Controllers
{
    public class ReportsController : ApiController
    {
        [HttpGet]
        public async Task<IHttpActionResult> GetReports()
        {
            Guid workspaceId = Guid.Parse(ConfigurationManager.AppSettings["powerbi:WorkspaceId"]);
            var devToken = PowerBIToken.CreateDevToken(ConfigurationManager.AppSettings["powerbi:WorkspaceCollection"], workspaceId);
            using (var client = this.CreatePowerBIClient(devToken))
            {
                var reportsResponse = await client.Reports.GetReportsAsync();
                return Ok(reportsResponse.Value
                    .Select(report => new
                    {
                        workspaceId = workspaceId,
                        reportId = report.Id,
                        reportName = report.Name,
                        reportEmbedUrl = report.EmbedUrl,
                    }));
            }
        }

        private IPowerBIClient CreatePowerBIClient(PowerBIToken token)
        {
            var jwt = token.Generate(ConfigurationManager.AppSettings["powerbi:SigningKey"]);
            var credentials = new TokenCredentials(jwt, "AppToken");
            var client = new PowerBIClient(credentials)
            {
                BaseUri = new Uri(ConfigurationManager.AppSettings["powerbi:ApiUrl"])
            };

            return client;
        }
    }
}

appx/Power BI Embedded/powerbi-sample-app/powerbi-sample-app/Views/Dashboard/Index.cshtml
@section Breadcrumbs{
    <ol class="breadcrumb navbar-breadcrumb">
        <li>Dashboard</li>
    </ol>
}

<div class="side-body padding-top">
    <div class="row">
    </div>
    <div class="row  no-margin-bottom">
    </div>
</div>

appx/Power BI Embedded/powerbi-sample-app/powerbi-sample-app/Views/Dashboard/Report.cshtml
@model ReportViewModel

@section Breadcrumbs {
    <ol class="breadcrumb navbar-breadcrumb">
        <li>Reports</li>
        <li class="active">@Model.Report.Name</li>
    </ol>
}
<div class="side-body padding-top">
    @Html.PowerBIAccessToken(Model.AccessToken)
    @Html.PowerBIReportFor(m => m.Report, new { style = "height:87vh" })
</div>

appx/Power BI Embedded/powerbi-sample-app/powerbi-sample-app/Views/Dashboard/Upload.cshtml
@model ReportUploadModel
@section Breadcrumbs{
    <ol class="breadcrumb navbar-breadcrumb">
        <li>Reports</li>
        <li class="active">Upload Power BI Report</li>
    </ol>
}

<div class="side-body padding-top">
    <div class="container">
        <div>
            <div>
                <div class="row">
                    <div class="col-sm-12">
                        <div>
                            <div class="page-header">
                                <h1>Upload Custom Power BI Report</h1>
                                Upload your custom <b>Power BI</b> report to be embedded in the application. You have options how you share the availability of this report.
                            </div>
                            @using (Html.BeginForm("Upload", "Dashboard", FormMethod.Post, new { enctype = "multipart/form-data" }))
                            {
                                <div class="form_group file_select_group">
                                    <label for="PbixReport">Report File:</label>
                                    <div class="input-group">
                                        <input type="text" class="form-control" readonly>
                                        <span class="input-group-btn">
                                            <span class="btn btn-primary btn-file">
                                                Browse&hellip; <input type="file" name="PbixReport">
                                            </span>
                                        </span>
                                    </div>
                                </div>
                                <div class="form_group">
                                    <label for="ReportName">Name:</label>
                                    <input type="text" class="form-control" name="ReportName">
                                </div>
                                <div class="form_group">
                                    <label for="ReportCategory">Category:</label>
                                    @Html.DropDownList("ReportCategory", ViewBag.ReportCategory as IEnumerable<SelectListItem>, new { @class = "form-control" })
                                </div>
                                <div class="form_group">
                                    <label for="ReportName">or New Category:</label>
                                    <input type="text" class="form-control" name="NewReportCategory">
                                </div>
                                <div class="form_group">
                                    <label>Share:</label>
                                    <br />
                                    <label class="radio-inline"><input type="radio" name="ShareOption" checked>Private</label>
                                    <label class="radio-inline"><input type="radio" name="ShareOption">My Division</label>
                                    <label class="radio-inline"><input type="radio" name="ShareOption">All Company Users</label>
                                    <label class="radio-inline"><input type="radio" name="ShareOption">Everyone</label>
                                </div>
                                <br />
                                <button type="submit" class="btn btn-primary">Upload</button>
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script type="text/javascript">
        $(document).ready( function() {
            $(document).on('change', '.btn-file :file', function() {
                var input = $(this),
                    numFiles = input.get(0).files ? input.get(0).files.length : 1,
                    label = input.val().replace(/\\/g, '/').replace(/.*\//, '');
                input.trigger('fileselect', [numFiles, label]);
            });
            $('.btn-file :file').on('fileselect', function(event, numFiles, label) {

                var input = $(this).parents('.input-group').find(':text'),
                    log = numFiles > 1 ? numFiles + ' files selected' : label;

                if( input.length ) {
                    input.val(log);
                } else {
                    if( log ) alert(log);
                }

            });
            $("input[type=text]").first().focus();
        });
    </script>
}